pub mod ssrf;
pub mod xxe;
pub mod header_injection;
pub mod host_header;
pub mod request_smuggling;
pub mod open_redirect;
pub mod cors;
pub mod websocket;
pub mod dns_rebinding;

pub use ssrf::SsrfDetector;
pub use xxe::XxeDetector;
pub use header_injection::HeaderInjectionDetector;
pub use host_header::HostHeaderDetector;
pub use request_smuggling::RequestSmugglingDetector;
pub use open_redirect::OpenRedirectDetector;
pub use cors::CorsDetector;
pub use websocket::WebSocketDetector;
pub use dns_rebinding::DnsRebindingDetector;
